export const SEARCH_FIELD = "SEARCH_FIELD";
export const IS_PENDING = "IS_PENDING"

export const REQUEST_EVENTS = "REQUEST_EVENTS";
export const REQUEST_EVENTS_HOURLY = "REQUEST_EVENTS_HOURLY";
export const REQUEST_EVENTS_DAILY = "REQUEST_EVENTS_DAILY";

export const REQUEST_STATS = "REQUEST_STATS";
export const REQUEST_STATS_HOURLY = "REQUEST_STATS_HOURLY";
export const REQUEST_STATS_DAILY = "REQUEST_STATS_DAILY";

export const REQUEST_POI = "REQUEST_POI";

export const REQUEST_TIME_START = "REQUEST_TIME_START";
export const REQUEST_TIME_END = "REQUEST_TIME_END";